package com.wellcare.emerald.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Decisions implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Valid Relationship")
	private java.lang.String validRelationship;

	public Decisions() {
	}

	public java.lang.String getValidRelationship() {
		return this.validRelationship;
	}

	public void setValidRelationship(java.lang.String validRelationship) {
		this.validRelationship = validRelationship;
	}

	public Decisions(java.lang.String validRelationship) {
		this.validRelationship = validRelationship;
	}

}