package com.wellcare.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Applicant DOB")
	private java.time.LocalDate applicantDOB;
	@org.kie.api.definition.type.Label("Gender Type Code")
	private java.lang.String genderTypeCode;
	@org.kie.api.definition.type.Label("Line of Business")
	private java.lang.String lob;

	@org.kie.api.definition.type.Label("Applicant Identifiers")
	private java.util.List<com.wellcare.rules.ApplicantIdentifier> applicantIdentifiers;

	@org.kie.api.definition.type.Label("State")
	private java.lang.String state;

	@org.kie.api.definition.type.Label("Subscriber Type")
	@org.kie.api.definition.type.Description("In 834 INS01")
	private java.lang.String subscriberType;

	@org.kie.api.definition.type.Label("Transaction Type")
	private java.lang.String transactionType;

	@org.kie.api.definition.type.Label("Member Id")
	private java.lang.String memberId;

	@org.kie.api.definition.type.Label("Type of Relationship")
	@org.kie.api.definition.type.Description("In 834 field INS02")
	private java.lang.String relationshipType;

	@org.kie.api.definition.type.Label("Applicant Social Security Number")
	private java.lang.String applicantSSN;

	public Transaction() {
	}

	public java.time.LocalDate getApplicantDOB() {
		return this.applicantDOB;
	}

	public void setApplicantDOB(java.time.LocalDate applicantDOB) {
		this.applicantDOB = applicantDOB;
	}

	public java.lang.String getGenderTypeCode() {
		return this.genderTypeCode;
	}

	public void setGenderTypeCode(java.lang.String genderTypeCode) {
		this.genderTypeCode = genderTypeCode;
	}

	public java.lang.String getLob() {
		return this.lob;
	}

	public void setLob(java.lang.String lob) {
		this.lob = lob;
	}

	public java.util.List<com.wellcare.rules.ApplicantIdentifier> getApplicantIdentifiers() {
		return this.applicantIdentifiers;
	}

	public void setApplicantIdentifiers(
			java.util.List<com.wellcare.rules.ApplicantIdentifier> applicantIdentifiers) {
		this.applicantIdentifiers = applicantIdentifiers;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getSubscriberType() {
		return this.subscriberType;
	}

	public void setSubscriberType(java.lang.String subscriberType) {
		this.subscriberType = subscriberType;
	}

	public java.lang.String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(java.lang.String transactionType) {
		this.transactionType = transactionType;
	}

	public java.lang.String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(java.lang.String memberId) {
		this.memberId = memberId;
	}

	public java.lang.String getRelationshipType() {
		return this.relationshipType;
	}

	public void setRelationshipType(java.lang.String relationshipType) {
		this.relationshipType = relationshipType;
	}

	public java.lang.String getApplicantSSN() {
		return this.applicantSSN;
	}

	public void setApplicantSSN(java.lang.String applicantSSN) {
		this.applicantSSN = applicantSSN;
	}

	public Transaction(
			java.time.LocalDate applicantDOB,
			java.lang.String genderTypeCode,
			java.lang.String lob,
			java.util.List<com.wellcare.rules.ApplicantIdentifier> applicantIdentifiers,
			java.lang.String state, java.lang.String subscriberType,
			java.lang.String transactionType, java.lang.String memberId,
			java.lang.String relationshipType, java.lang.String applicantSSN) {
		this.applicantDOB = applicantDOB;
		this.genderTypeCode = genderTypeCode;
		this.lob = lob;
		this.applicantIdentifiers = applicantIdentifiers;
		this.state = state;
		this.subscriberType = subscriberType;
		this.transactionType = transactionType;
		this.memberId = memberId;
		this.relationshipType = relationshipType;
		this.applicantSSN = applicantSSN;
	}

}