package com.wellcare.rules;

/*import com.wellcare.rules.Transaction;
import com.wellcare.rules.RuleMessage;
import java.time.LocalDate;


rule "Relationship Rule"
    ruleflow-group "CARelationshipRules1"
    when
        txn : Transaction( state == "CA"  )
        
    then
        if ()
        
		RuleMessage msg = new RuleMessage();
		msg.setMessageCode("010");
		msg.setMessageText("Dependent Rules Executed");
		insert(msg);
			
end
*/