package com.wellcare.rules;

import com.wellcare.rules.Transaction;
import com.wellcare.rules.RuleMessage;
import java.time.LocalDate;





rule "Reinstatement Rule"
    ruleflow-group "ReinstatementRules"
    when
        txn : Transaction( subscriberType == "Reinstatement"  )
        
    then
		RuleMessage msg = new RuleMessage();
		msg.setMessageCode("013");
		msg.setMessageText("Reinstatement Rules Executed");
		insert(msg);
			
end